stages:
- build

build_main:
  stage: build
  script:
    - git clone https://gitlab.com/g76r/libqtssu.git
    - cd libqtssu && qmake && make && cd ..
    - qmake INCLUDEPATH+=libqtssu LIBS+=libqtssu
    - make
  tags:
    - qt
    - c++
